[workspace]
resolver = "2"
members = ["data_scraper"]

[workspace.dependencies]
tokio = { version = "1.37.0", features = ["full"] }
env_logger = "0.11.3"
openssl = { version = "0.10.64", features = ["vendored"] }
